# Generated by Django 5.2.8 on 2025-11-13 04:18

import django.db.models.deletion
import django_enum.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "category_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("category_name", models.CharField(max_length=20)),
                ("main_image", models.BinaryField(blank=True)),
                ("description", models.TextField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "location_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("province", models.CharField(max_length=20)),
                ("city", models.CharField(max_length=20)),
                ("town", models.CharField(max_length=20)),
                ("description", models.TextField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="UserDetail",
            fields=[
                (
                    "user_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("user_name", models.CharField(max_length=20)),
                ("bio", models.TextField(blank=True, max_length=100)),
                ("invite_code", models.CharField(max_length=20)),
                ("profile_image", models.BinaryField(blank=True)),
                ("date_of_birth", models.DateField()),
                ("time_created", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Authentication",
            fields=[
                (
                    "auth_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "type",
                    django_enum.fields.EnumCharField(
                        choices=[("kakao", "KAKAO"), ("naver", "NAVER")], max_length=5
                    ),
                ),
                ("token", models.CharField(blank=True, max_length=100)),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("type__in", ["kakao", "naver"])),
                        name="api_Authentication_type_AuthType",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="EventDetail",
            fields=[
                (
                    "event_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("event_name", models.CharField(max_length=50)),
                ("description", models.TextField(blank=True, max_length=200)),
                ("main_image", models.BinaryField(blank=True)),
                ("capacity", models.IntegerField()),
                ("duration", models.IntegerField()),
                (
                    "status",
                    django_enum.fields.EnumCharField(
                        choices=[
                            ("planned", "PLANNED"),
                            ("ongoing", "ONGOING"),
                            ("completed", "COMPLETED"),
                            ("cancelled", "CANCELLED"),
                        ],
                        default="planned",
                        max_length=9,
                    ),
                ),
                ("address", models.CharField(max_length=100)),
                ("time_created", models.DateTimeField(auto_now_add=True)),
                ("time_updated", models.DateTimeField(auto_now=True)),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "status__in",
                                ["planned", "ongoing", "completed", "cancelled"],
                            )
                        ),
                        name="api_EventDetail_status_EventStatus",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="EventCategory",
            fields=[
                (
                    "event_category_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "category_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.category"
                    ),
                ),
                (
                    "event_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.eventdetail",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EventLog",
            fields=[
                (
                    "event_log_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("datetime", models.DateTimeField()),
                ("description", models.TextField(blank=True, max_length=100)),
                (
                    "event_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.eventdetail",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EventLogNotification",
            fields=[
                (
                    "notification_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("detail", models.TextField(blank=True, max_length=200)),
                ("time_created", models.DateTimeField(auto_now_add=True)),
                (
                    "event_log_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.eventlog"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EventLocation",
            fields=[
                (
                    "event_location_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "event_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.eventdetail",
                    ),
                ),
                (
                    "location_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.location"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserAuthentication",
            fields=[
                (
                    "user_auth_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "auth_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.authentication",
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.userdetail"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EventOrganizer",
            fields=[
                (
                    "event_organizer_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "event_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.eventdetail",
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.userdetail"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserEvent",
            fields=[
                (
                    "user_event_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("time_joined", models.DateTimeField(auto_now_add=True)),
                (
                    "event_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.eventdetail",
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.userdetail"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserEventLog",
            fields=[
                (
                    "user_event_log_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("has_checked_in", models.BooleanField(default=False)),
                (
                    "user_event_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.userevent"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserLocation",
            fields=[
                (
                    "user_location_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "location_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.location"
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.userdetail"
                    ),
                ),
            ],
        ),
    ]
