# Generated by Django 5.2.8 on 2025-12-16 18:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_rename_user_name_userdetail_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventdetail",
            name="is_featured",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="eventdetail",
            name="view_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="eventnotification",
            name="from_admin",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userdetail",
            name="expo_push_token",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="userdetail",
            name="last_login",
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
