# Generated by Django 5.2.8 on 2025-12-21 20:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_eventdetail_is_featured_eventdetail_view_count_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="authentication",
            name="provider_access_token",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="authentication",
            name="provider_access_token_expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="authentication",
            name="provider_refresh_token",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="authentication",
            name="provider_refresh_token_expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="authentication",
            name="provider_user_id",
            field=models.TextField(blank=True),
        ),
        migrations.RemoveField(
            model_name="authentication",
            name="token",
        ),
        migrations.AlterUniqueTogether(
            name="authentication",
            unique_together={("type", "provider_user_id")},
        ),
    ]
