# Generated by Django 5.2.8 on 2025-12-27 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_alter_authentication_unique_together_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="authentication",
            name="api_Authentication_type_AuthType",
        ),
        migrations.RenameField(
            model_name="authentication",
            old_name="type",
            new_name="auth_type",
        ),
        migrations.AlterUniqueTogether(
            name="authentication",
            unique_together={("auth_type", "provider_user_id")},
        ),
        migrations.AddConstraint(
            model_name="authentication",
            constraint=models.CheckConstraint(
                condition=models.Q(("auth_type__in", ["kakao", "naver"])),
                name="api_Authentication_auth_type_AuthType",
            ),
        ),
    ]
