# Generated by Django 5.2.8 on 2025-12-27 21:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0005_remove_authentication_api_authentication_type_authtype_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userdetail",
            name="date_of_birth",
            field=models.DateField(blank=True),
        ),
    ]
