# Generated by Django 5.2.8 on 2025-12-27 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_alter_userdetail_date_of_birth"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userdetail",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True),
        ),
    ]
