# Generated by Django 5.2.8 on 2026-01-01 08:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0007_alter_userdetail_date_of_birth"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userdetail",
            name="last_login",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
