# Generated by Django 5.2.8 on 2025-12-30 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_alter_userdetail_date_of_birth"),
    ]

    operations = [
        migrations.AddField(
            model_name="userdetail",
            name="age_range",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
